### ISSUE TITLE
[Web player] Unexpected Shuffle button behaviour

### ISSUE THREAD

**Issue by poisonborz** [ironsmile/euterpe#31]
In most audio players, the Shuffle button toggles an option wether the next track should be according to the playlist or a random song. In Euterpe, it immediately plays a random song, which is unexpected, and therefore undesireable. It is also confusing since the Repeat button besides it is simply a toggle as it should (instead of also immediately restarting the current song).

**Comment by ironsmile** [comment]
Yes, having inconsistent behaviour for the button is a drag. I haven't noticed it before since it has always been like this for me!

Anyway, I am leaning more towards making both buttons a toggle which does not immediately change the currently playing track. This will be consistent with the rest of the clients.
