### ISSUE TITLE
Image for arm architecture?

### ISSUE THREAD

**Issue by VlaK0r** [ironsmile/euterpe#56]
Hello!
Thank you for your hard work!
Please tell me how to make an image for arm architecture?

**Comment by ironsmile** [comment]
Hello! I was able to simply build an ARMv8 version by simply using the [Dockerfile](https://github.com/ironsmile/euterpe/blob/master/Dockerfile) from the repository root on my arm64v8 device with postmarketOS:

```sh
docker build --network host --rm -t ironsmile/euterpe:v1.5.4-arm64v8 .
```

And since I've done that already, I've uploaded the image to the Docker hub under the [v1.5.4-arm64v8 tag](https://hub.docker.com/layers/ironsmile/euterpe/v1.5.4-arm64v8/images/sha256-fd542c302ee64a505a9899b207ed7a52b6af2cdb8e6e2d71fe303bcc46a11ba8?context=repo). You can get it by running

```sh
docker pull ironsmile/euterpe:v1.5.4-arm64v8
```

If your device has a different type of ARM processor then you could build it yourself, I hope.
