### ISSUE TITLE
Make WebUI source easily accessible

### ISSUE THREAD

**Issue by Utoog** [ironsmile/euterpe#58]
Maybe you can add that contents of the webui are in some folder so you can change something without recompiling whole app?

**Comment by ironsmile** [comment]
Hello! There's the `-local-fs` flag already which was not originally designed for what you want to achieve but it will happily do it:

```
$ euterpe -h
[...]
  -local-fs
    	Will use local files for SQL templates, HTML templates and static files.
    	As opposed to the bundled into the binary versions. Useful for development.
[...]
```

Unfortunately it works requires a bunch of directories to be present, not only the web UI. But they are not much and you could download it from the repository. So you could copy the `templates`, `sqls` and `http_root` directories somewhere and then run `euterpe -local-fs` with the current directory set to where you've downloaded the files. Here's how you could do it in few steps:

```
git clone -n --depth=1 --filter=tree:0 https://github.com/ironsmile/euterpe.git euterpe-local-files
cd euterpe-local-files/
git sparse-checkout set --no-cone http_root sqls templates
git checkout
euterpe -local-fs
```

Some notes:

* The HTML templates are in `templates`
* The JS, CSS, images and everything else is in the `http_root`
* By default the HTML templates include the minified versions of javascript and JS files but you could easily change this as you will control the `layout.html` template as well
* In the `http_root` there's a bash script `squash` which produces the combined JS and CSS files if you decide to keep using them

Overall, this should work just fine for the time being. But the static files are not normally kept outside of the binary since they are likely to change on every new release. If they were outside of the binary there are two scenarios which will on new Euterpe version:

* New versions do not replace the files on disk. Which means they are broken and the web UI does not work.
* New versions replace the files on disk. Which means the UI works but any local modifications are lost. So nothing better than the current situation where the UI files are bundled in.

So that's why files are embedded. Also, having just a single binary to deal with makes life very simple!

I hope this helps you. But I am not promising to keep old UI files working in newer versions. If you choose to keep your local modifications you will have to be responsible for them.

That being said, your request gives me an idea for formally introducing a "sinks" feature. Where some convention could be arranged where skinning is possible by introducing user themes. We shall see!

Good day!

**Comment by Utoog** [comment]
Thanks! What changes i should to to systemd service so it can work?

**Comment by ironsmile** [comment]
You should change the `WorkingDirectory` and `ExecStart` under the `[Service]` section. Something like this:

```
[Service]
ExecStart=/usr/bin/euterpe -local-fs
WorkingDirectory=/path/to/euterpe-local-files
```

**Comment by Utoog** [comment]
Thank you very much! it was very helpful
